SELECT DISTINCT Director FROM movies ORDER BY Director ASC;
SELECT Title FROM movies ORDER BY Year DESC LIMIT 4;
SELECT Title FROM movies ORDER BY Title ASC LIMIT 5;
SELECT Title FROM movies ORDER BY Title ASC LIMIT 5 OFFSET 5;
